<?php
// +----------------------------------------------------------------------
// | 部门
// +----------------------------------------------------------------------
// | Author: wk <weika520@qq.com | http://www.wcphp.com> 2017/7/21 16:13
// +----------------------------------------------------------------------

namespace app\api\controller;

use app\common\controller\AuthBase;
use app\common\model\Department as DepartmentModel;
use think\Request;

class DepartmentController extends AuthBase
{
    public  $departmentModel;
    public function __construct(Request $request)
    {
        parent::__construct($request); // TODO: Change the autogenerated stub
        $this->departmentModel = new DepartmentModel();
    }
    /**
     * 部门列表
     * Author: wk <weika520@qq.com>
     */
    public function lists()
    {
            $map = [
                'search_word/s'=>'search_word',
                'page/d'=>['page',1],
                'page_size/d'=>'page_size',
            ];
            $data = $this->getParams($map);
            $searchData = $this->departmentModel->searchQuery($data);
            apiSuccess('success',$searchData);
    }

    /**
     * 添加部门
     * Author: wk <weika520@qq.com>
     */
    public function add()
    {
        $map = [
            'Fname/s'=>'name',
            'Fdesc/s'=>'desc',
        ];
        $data = $this->getParams($map,'Department.add');

        $result = $this->departmentModel->create($data);
         if(isset($result->Fdepartment_id)){
             apiSuccess('添加部门成功',['department_id'=>$result->Fdepartment_id]);
         }
        apiFail('10009','添加部门失败');

    }
    /**
     * 查询单个部门信息
     * Author: wk <weika520@qq.com>
     */
    public function info()
    {
        $map = [
            'Fdepartment_id/d'=>'department_id',
        ];
        $data = $this->getParams($map,'Department.info');

        $result = $this->departmentModel->setFieldMap(['department_id','name','desc'])->find($data);
        if(!empty($result)){
            apiSuccess('获取部门信息成功',$result->toArray());
        }else{
            apiFail('10009','获取部门信息不存在');
        }
    }

    /**
     * 修改部门信息
     * Author: wk <weika520@qq.com>
     */
    public function edit()
    {
        $map = [
            'Fdepartment_id/d'=>'department_id',
            'Fname/s'=>'name',
            'Fdesc/s'=>'desc',
        ];
        $data = $this->getParams($map,'Department.edit');
        $result = $this->departmentModel->update($data);
        apiSuccess('修改部门信息成功');
    }

    /**
     * 删除部门信息
     * Author: wk <weika520@qq.com>
     */
    public function del()
    {
        $map = [
            'ids'=>'department_id',
        ];
        $data = $this->getParams($map,'Department.del');
        /*if(is_array($data['ids'])){
            $where['Fdepartment_id'] = ['in',$data['ids']];
        }else{
            $where['Fdepartment_id'] = $data['ids'];
        }*/

        $result = $this->departmentModel->where(['Fdepartment_id'=>['in',$data['ids']]])->delete();
        if($result >0){
            apiSuccess('删除部门信息成功');
        }
        apiFail('10009','删除部门消息失败');
    }

    /**
     * 部门(选择)
     * Author: wk <weika520@qq.com>
     */
    public function departmentSelect()
    {
        $departmentList = $this->departmentModel->setFieldMap(['name','department_id'])->select();
        $lists = [];
        if(!empty($departmentList)){
            foreach($departmentList as $item){
                $lists[] = $item->toArray();
            }
        }
        apiSuccess('获取部门成功',['lists'=>$lists]);
    }




}