<?php
// +----------------------------------------------------------------------
// | 
// +----------------------------------------------------------------------
// | Author: wk <weika520@qq.com | http://www.wcphp.com> 2017/7/27 9:24
// +----------------------------------------------------------------------

namespace app\api\controller;


use app\common\controller\AuthBase;
use app\common\model\System as SystemModel;
use think\Db;
use think\Request;

class SystemController extends AuthBase
{
    public  $systemModel;
    public function __construct(Request $request)
    {
        parent::__construct($request); // TODO: Change the autogenerated stub
        $this->systemModel = new SystemModel();
    }
    /**
     * 系统列表
     * @param mixed
     * Author: wk <weika520@qq.com>
     */
    public function lists()
    {
        $map = [
            'search_word/s'=>'search_word',
            'page/d'=>['page',1],
            'page_size/d'=>'page_size',
        ];
        $data = $this->getParams($map);
        $searchData = $this->systemModel->searchQuery($data);
        apiSuccess('success',$searchData);
    }
    /**
     * 添加系统
     * Author: wk <weika520@qq.com>
     */
    public function add()
    {
        $map = [
            'Fname/s'=>'name',
            'Furl/s'=>'url',
            'Fsystem_desc/s'=>'system_desc',
        ];
        $data = $this->getParams($map,'System.add');
        $result = $this->systemModel->create($data);
        if(isset($result->Fsystem_id)){
            apiSuccess('添加系统成功');
        }
        apiFail('10009','添加系统失败');

    }
    /**
     * 查询单个系统信息
     * Author: wk <weika520@qq.com>
     */
    public function info()
    {
        $map = [
            'Fsystem_id'=>'system_id',
        ];
        $data = $this->getParams($map,'System.info');
        $result = $this->systemModel->setFieldMap(['system_id','name','url','system_desc'])->find($data);
        if(!empty($result)){
            apiSuccess('获取系统信息成功',$result->toArray());
        }else{
            apiFail('10009','获取系统信息不存在');
        }
    }

    /**
     * 修改系统信息
     * Author: wk <weika520@qq.com>
     */
    public function edit()
    {
        $map = [
            'Fsystem_id'=>'system_id',
            'Fname/s'=>'name',
            'Furl/s'=>'url',
            'Fsystem_desc/s'=>'system_desc',
        ];
        $data = $this->getParams($map,'System.edit');
        $result = $this->systemModel->isUpdate(true)->save($data);
        if($result >0){
            apiSuccess('修改系统信息成功');
        }else{
            apiFail('10009','修改系统信息失败');
        }
    }

    /**
     * 删除系统信息
     * Author: wk <weika520@qq.com>
     */
    public function del()
    {
        $map = [
            'ids'=>'system_id',
        ];
        $data = $this->getParams($map,'System.del');
        $result = $this->systemModel->destroy($data['ids']);
        if($result >0){
            apiSuccess('删除系统成功');
        }
        apiFail('10009','删除系统失败');
    }

    /**
     * 系统选择
     * Author: wk <weika520@qq.com>
     */
    public function systemSelect()
    {
        //所有系统
        $systemList = $this->systemModel->setFieldMap(['system_id','name'])->select();
        $role = Db::name('role')->field(['Frole_id'=>'role_id','Fname'=>'name','Fsystem_id'=>'system_id'])->select();
        //所有角色
        $lists = [];
        if(!empty($systemList)){
            foreach($systemList as $item){
                $system = $item->toArray();
                $roleList = [];
                if(!empty($role)){
                   foreach($role as $value){
                        if($system['system_id'] == $value['system_id'])
                            $roleList[] =  $value;
                   }
                }
                $system['role_list'] = $roleList;
                $lists[] = $system;
            }
        }
        apiSuccess('获取系统成功',['lists'=>$lists]);
    }

}